version: '3.1'
services:
  api-reservations:
    image: adschosen/api-reservations:1.0.0
    container_name: api-reservations
    ports:
      - 8080:8080
    restart: always

  api-catalog:
    image: adschosen/api-catalog:1.1.0
    container_name: api-catalog
    ports:
     - 6070:6070
    restart: always 
    links:
      - api-catalog-db
      
  api-catalog-db:
    container_name: api-catalog-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_catalog'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
      - 3310:3306
